### ISSUE TITLE
Cannot run examples using ktx.dll

### ISSUE THREAD

**Issue by LucadeRaad** [JuanDiegoMontoya/Fwog#103]
Instead of running:
`$ cmake ..`
as the final step of building fwog I used cmake-gui to turn on the examples (only thing I changed):
![image](https://github.com/user-attachments/assets/fe2a8be7-6ceb-4531-9341-45bd69e18e41)

when I try to run example 3 which relies on ktx.dll it fails:
![image](https://github.com/user-attachments/assets/a5830f1d-a5c1-4403-a628-5344c33c28e2)

this is true of other examples that rely on ktx.dll

**Comment by JuanDiegoMontoya** [comment]
Hi @LucadeRaad, I wasn't able to reproduce your error. To weed out potential issues, I have a few questions:

1. What version of CMake are you using? I'm on 3.26.3.
2. What build system are you generating project files for? I'm targeting Visual Studio 17 2022 on my PC.

One thing you can try to resolve the issue is to enable `KTX_FEATURE_STATIC_LIBRARY`. It should show up in cmake-gui after you click Configure or Generate. Then, you can generate the project files and attempt to compile again.
![image](https://github.com/user-attachments/assets/6e57111d-4370-4552-b3e7-e84d6a247ffa)

**Comment by LucadeRaad** [comment]
Thanks for the reply, turning on the static library worked

one thing I noticed: changing the CMake version didn't matter but 3.28 and 3.30 caused a lot of cmake warnings regarding deprecated features that did not show up with CMake 3.26

**Comment by JuanDiegoMontoya** [comment]
I'm glad it worked! Also, thanks for letting me know about the CMake warnings. I'll upgrade and check those out.
